; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Generate compile_commands.json for clangd
extra_configs = platformio_local.ini

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
upload_speed = 1500000

; Generate compile_commands.json on build
extra_scripts = pre:scripts/generate_compiledb.py
lib_deps =
    m5stack/M5Unified@^0.2.2
    m5stack/M5GFX@^0.2.3
    hideakitai/ArduinoOSC@^0.4.0
    bblanchon/ArduinoJson@^7.0.0

build_flags =
    -DCORE_DEBUG_LEVEL=3

board_build.partitions = partitions.csv
board_build.filesystem = spiffs

[env:m5stick-c-plus]
board = m5stick-c
board_build.variant = m5stack_stickc_plus
build_flags =
    ${env.build_flags}
    -DARDUINO_M5STICK_C_PLUS

[env:m5stick-c]
board = m5stick-c
board_build.variant = m5stack_stickc
build_flags =
    ${env.build_flags}
    -DARDUINO_M5STICK_C

[env:m5stack-core2]
board = m5stack-core2
build_flags =
    ${env.build_flags}
    -DARDUINO_M5STACK_CORE2
